### ISSUE TITLE
Author not shown in lexicon explorer after lexical entry creation

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#79]
As title
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/bc2bd737-bcea-4600-bc5b-3c337e650f48)
After a reload/refresh of the lexicon explorer the author icon is correctly shown

**Comment by MPapini91** [comment]
Probably the problem is related to the fact that the new item is inserted into the tree from the interface and lacks the complete data returned from the backend. In this case, an update of the list would be required for proper display, with its advantages and disadvantages.

#########################################

Probabilmente il problema è legato al fatto che il nuovo elemento viene inserito nell'albero dall'interfaccia e manca dei dati completi restituiti dal backend. In questo caso, per una corretta visualizzazione sarebbe necessario un aggiornamento dell'elenco, con i relativi vantaggi e svantaggi.
